# Generated by Django 4.2.1 on 2023-06-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_chaukos_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaukos',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
