# Generated by Django 4.2.1 on 2023-06-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_remove_chaukos_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModularItems',
            new_name='ModularItem',
        ),
    ]
