# Generated by Django 4.2.1 on 2023-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_rename_modularitems_modularitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
