# Generated by Django 4.2.1 on 2023-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_furnitureitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaukos',
            name='imageC',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='modularitem',
            name='imageMK',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnitureitems',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
