# Generated by Django 4.2.1 on 2023-06-07 06:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_chaukos_imagec_modularitem_imagemk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(choices=[('Kathmandu', 1), ('Bhaktapur', 2), ('Lalitpur', 3)], max_length=50)),
                ('interested_item', models.CharField(max_length=100)),
                ('localAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
